# Generated by Django 5.2.3 on 2025-06-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StandchenAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filepath", models.CharField(max_length=4096, unique=True)),
                ("name", models.CharField(max_length=256)),
                ("length", models.IntegerField(null=True)),
            ],
        ),
    ]
