# Generated by Django 5.2.12 on 2026-03-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standchenaudio",
            name="length",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
