# Generated by Django 5.2.12 on 2026-03-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0002_alter_standchenaudio_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("tracks", models.ManyToManyField(to="player.standchenaudio")),
            ],
        ),
    ]
